 version: '3'
 
 services:
  arangodb:
    hostname: arangodb
    image: arangodb/arangodb
    ports:
      - 8529:8529
    volumes:
      - ./db:/var/lib/arangodb3
      - ./apps:/var/lib/arangodb3-apps
    environment:
      ARANGO_NO_AUTH: 1